### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by tszmyt-creatuity** [creatuity/magento2-order-status-adjust#12]
We need to perform full QA of the entire module.

During QA, please refer to README.md contents: https://github.com/creatuity/magento2-order-status-adjust/blob/main/README.md

**Comment by creatuitydevelopers** [comment]
Tests completed.
[Local tests of whole module according to the documentation - TestRail.pdf](https://github.com/creatuity/magento2-order-status-adjust/files/12310452/Local.tests.of.whole.module.according.to.the.documentation.-.TestRail.pdf)

**Comment by tszmyt-creatuity** [comment]
Closing this one
